**최적화된 혈당 보정 모델 무누수 통합 파이프라인**

독립적인 정규화, 데이터 증강, Conv1D 보정 모델 학습 및 임베디드 배포용 TFLite 변환을 단일 흐름으로 수행

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import os
import json
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler

# 1. 환경 초기화 및 시드 고정
np.random.seed(42)
tf.random.set_seed(42)

SAVE_DIR = '/content/drive/MyDrive/Glucose_Model_Output'
os.makedirs(SAVE_DIR, exist_ok=True)

# 2. 안전한 전용 데이터 로드 및 경로 탐색 (드라이브 마운트 코드 제거 및 가상 모사 데이터 자가치유 완전 배제)
candidate_paths = [
    '/content/drive/MyDrive/data/예시_frames_v1.csv',
    '/content/drive/MyDrive/ai_model/data/examples/예시_frames_v1.csv',
    '/content/drive/MyDrive/예시_frames_v1.csv'
]

drive_csv_path = None
for path in candidate_paths:
    if os.path.exists(path):
        drive_csv_path = path
        break

if drive_csv_path is None:
    raise FileNotFoundError("구글 드라이브 내 'data' 폴더 혹은 지정 경로 내에서 '예시_frames_v1.csv' 파일을 찾을 수 없습니다. 드라이브가 제대로 마운트되었는지 확인해 주세요.")

print(f"[로드 확인] 데이터 소스 경로: {drive_csv_path}")
drive_df = pd.read_csv(drive_csv_path)
print(f"최종 활성화 원본 데이터 규격: {drive_df.shape}")

# 신규 [1, 7, 1] 입력 규격을 위한 정확한 피처 슬라이싱 (NIR 3개 + S21 4개)
feature_cols = ['A_1310', 'A_1370', 'A_1625', 'S21_dB_f1', 'S21_dB_f2', 'S21_dB_f3', 'S21_dB_f4']
target_col = 'glucose_mgdl'

# 타입 안전 수치 변환
for col in feature_cols + [target_col]:
    drive_df[col] = pd.to_numeric(drive_df[col], errors='coerce')
drive_df = drive_df.dropna(subset=[target_col]).fillna(0)

# 3. 엄격한 세션 기반 분할 (Session-based Split) - 행 단위 무작위 셔플 누수 방지
unique_sessions = sorted(drive_df['session'].unique())
test_sessions = [unique_sessions[-1]]  # 마지막 세션 독립 격리
train_sessions = [s for s in unique_sessions if s not in test_sessions]

train_df = drive_df[drive_df['session'].isin(train_sessions)].copy()
test_df = drive_df[drive_df['session'].isin(test_sessions)].copy()

X_train_raw = train_df[feature_cols].values
y_train_raw = train_df[target_col].values
X_test_raw = test_df[feature_cols].values
y_test_raw = test_df[target_col].values

print(f"분할 결과: 학습 세션 {train_sessions} ({X_train_raw.shape[0]}행) / 테스트 세션 {test_sessions} ({X_test_raw.shape[0]}행)")

# 4. 정규화 적합 제한 규칙 (StandardScaler fitting strictly on training set)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_raw)
X_test_scaled = scaler.transform(X_test_raw)

# 배포용 스케일러 파라미터 (mean, scale) 저장
scaler_params = {
    "mean": scaler.mean_.tolist(),
    "scale": scaler.scale_.tolist()
}
with open(os.path.join(SAVE_DIR, "scaler_params.json"), "w") as f:
    json.dump(scaler_params, f, indent=4)
print(f"배포용 스케일러 파라미터 내보내기 성공: {SAVE_DIR}/scaler_params.json")

[로드 확인] 데이터 소스 경로: /content/drive/MyDrive/data/예시_frames_v1.csv
최종 활성화 원본 데이터 규격: (90, 37)
분할 결과: 학습 세션 [np.int64(0), np.int64(1)] (60행) / 테스트 세션 [np.int64(2)] (30행)
배포용 스케일러 파라미터 내보내기 성공: /content/drive/MyDrive/Glucose_Model_Output/scaler_params.json

In [10]:
import os
import pandas as pd

# 구글 드라이브 내 data 폴더 파일이 올바르게 로드되었는지 확인
expected_path = '/content/drive/MyDrive/data/예시_frames_v1.csv'
if os.path.exists(expected_path):
    print(f"[검증 완료] 지정된 경로가 정확히 존재합니다: {expected_path}")
    check_df = pd.read_csv(expected_path)
    print(f"데이터 크기 (행, 열): {check_df.shape}")
    print("\n--- 로드된 데이터 상위 5개 행 샘플 ---")
    display(check_df.head(5))
else:
    print(f"[오류] {expected_path} 경로에 파일이 존재하지 않습니다. 드라이브 내부 경로를 다시 한 번 확인해주세요.")

[검증 완료] 지정된 경로가 정확히 존재합니다: /content/drive/MyDrive/data/예시_frames_v1.csv
데이터 크기 (행, 열): (90, 37)

--- 로드된 데이터 상위 5개 행 샘플 ---

,session,frame,t_s,wear_min,A_1310,A_1370,A_1625,S21_dB_f1,S21_dB_f2,S21_dB_f3,...,sigma_A_1310,sigma_A_1370,sigma_A_1625,sigma_S21_dB,sigma_S21_deg,sigma_ntc_C,sigma_fsr_N,n_avg,frame_period_s,design
0,0,0,0,5.000000,-0.022414,-0.043906,-0.045904,-5.649334,-5.695201,-5.765537,...,0.000304,0.000305,0.000305,0.000079,0.000216,0.05,0.067861,860,20,1
1,0,1,20,5.333333,-0.021838,-0.043544,-0.047137,-5.649572,-5.695561,-5.765881,...,0.000304,0.000305,0.000305,0.000079,0.000216,0.05,0.069229,860,20,1
2,0,2,40,5.666667,-0.022543,-0.042250,-0.048220,-5.650016,-5.695823,-5.765956,...,0.000304,0.000305,0.000305,0.000079,0.000216,0.05,0.070537,860,20,1
3,0,3,60,6.000000,-0.022418,-0.042388,-0.048664,-5.650149,-5.696159,-5.766229,...,0.000304,0.000305,0.000305,0.000079,0.000216,0.05,0.071789,860,20,1
4,0,4,80,6.333333,-0.022145,-0.041643,-0.048991,-5.650274,-5.696195,-5.766348,...,0.000304,0.000305,0.000305,0.000079,0.000216,0.05,0.072991,860,20,1

In [11]:
import os
import pandas as pd

data_dir = '/content/drive/MyDrive/data'
if os.path.exists(data_dir):
    files = os.listdir(data_dir)
    print(f"data 폴더 내 전체 파일 목록: {files}")

    csv_files = [f for f in files if f.endswith('.csv')]
    print(f"발견된 CSV 파일 목록: {csv_files}")

    for csv_file in csv_files:
        file_path = os.path.join(data_dir, csv_file)
        try:
            temp_df = pd.read_csv(file_path)
            print(f"\n=== 파일명: {csv_file} (크기: {temp_df.shape}) ===")
            print("컬럼 목록:", list(temp_df.columns))
            display(temp_df.head(2))
        except Exception as e:
            print(f"파일 {csv_file} 로드 실패: {e}")
else:
    print(f"디렉토리가 존재하지 않습니다: {data_dir}")

data 폴더 내 전체 파일 목록: ['압력층_v1.csv', 'EM_계수표_v1.csv', '알고리즘_입력형식_기본안_v1.md', 'HW_노이즈_v1.csv', 'HW_노이즈_v1.md', 'EM_계수표_v1.md', '압력층_v1.md', '읽기방식_v1.csv', '광자수송_v1.md', 'NIR_계수표_v1.md', '벤치예측_v1.md', '예시_frames_v1.csv', 'NIR_계수표_v1.csv', '통합모델_v1.md', '통합모델_v1.csv', '회로대조_v1.md', '구조비교_v1.csv', '구조비교_v1_results.json', 'README.md', 'EM_구조비교_v1.md', '예시_frames_flag_v1.csv', 'em_coeff_S11_v1_spectra.csv', '광자수송_v1.csv', 'Glucose_Level_Estimation.csv']
발견된 CSV 파일 목록: ['압력층_v1.csv', 'EM_계수표_v1.csv', 'HW_노이즈_v1.csv', '읽기방식_v1.csv', '예시_frames_v1.csv', 'NIR_계수표_v1.csv', '통합모델_v1.csv', '구조비교_v1.csv', '예시_frames_flag_v1.csv', 'em_coeff_S11_v1_spectra.csv', '광자수송_v1.csv', 'Glucose_Level_Estimation.csv']

=== 파일명: 압력층_v1.csv (크기: (66, 6)) ===
컬럼 목록: ['table', 'label', 'value_a', 'value_b', 'value_c', 'note']

,table,label,value_a,value_b,value_c,note
0,operating_point,gap 3.5 mm,1.0,0.081781,0.083145,force N / sigma_force N / sigma_thickness mm
1,operating_point,gap 3.75 mm,1.25,0.102226,0.102500,force N / sigma_force N / sigma_thickness mm

=== 파일명: EM_계수표_v1.csv (크기: (6, 19)) ===
컬럼 목록: ['항목', '단위', 'S21 곡선 이동 (MHz/단위)', '이동 se', 'S21 Q 변화/단위', 'Δ|S21| dB @2.30', 'Δ|S21| dB @2.36', 'Δ|S21| dB @2.42', 'Δ|S21| dB @2.48', 'Δ|S21| dB @2.54', 'Δ|S21| dB @2.60', 'Δ위상 ° @2.30', 'Δ위상 ° @2.36', 'Δ위상 ° @2.42', 'Δ위상 ° @2.48', 'Δ위상 ° @2.54', 'Δ위상 ° @2.60', '잔차비', '비고']

,항목,단위,S21 곡선 이동 (MHz/단위),이동 se,S21 Q 변화/단위,Δ|S21| dB @2.30,Δ|S21| dB @2.36,Δ|S21| dB @2.42,Δ|S21| dB @2.48,Δ|S21| dB @2.54,Δ|S21| dB @2.60,Δ위상 ° @2.30,Δ위상 ° @2.36,Δ위상 ° @2.42,Δ위상 ° @2.48,Δ위상 ° @2.54,Δ위상 ° @2.60,잔차비,비고
0,혈액 εr,Δεr = +1,-4.70143,0.334200,0.035740,0.010533,0.010363,0.008878,0.006646,0.004072,0.001068,0.010160,-0.019622,-0.046570,-0.069440,-0.090208,-0.112278,0.213,NaN
1,혈액 κ,Δκ = +1 S/m,1.89315,10.253333,-0.443666,-0.000509,-0.038680,-0.067725,-0.087607,-0.103588,-0.121784,-0.598098,-0.531267,-0.396777,-0.245379,-0.104950,0.037413,0.998,NaN

=== 파일명: HW_노이즈_v1.csv (크기: (93, 5)) ===
컬럼 목록: ['표', '항목', '세부', '값', '단위']

           표       항목   세부        값  단위
0  NIR 기준 신호  1310 nm    T   0.0994   -
1  NIR 기준 신호  1310 nm  광전류  96.4350  nA

=== 파일명: 읽기방식_v1.csv (크기: (51, 9)) ===
컬럼 목록: ['table', 'label', 'point', 'sigA_1310_mAU', 'sigA_1370_mAU', 'sigA_1625_mAU', 'glucose_sigma_a', 'glucose_sigma_b', 'note']

,table,label,point,sigA_1310_mAU,sigA_1370_mAU,sigA_1625_mAU,glucose_sigma_a,glucose_sigma_b,note
0,methods,"direct (빛 − 어둠, 기본값)","현재 설계 (50회, ±2.048 V 고정)",0.3175,0.5246,0.7473,607.6,12.3,conversions per LED 2; a = NIR only (temperatu...
1,methods,"direct (빛 − 어둠, 기본값)",범위 자동 + 860회,0.3044,0.3048,0.3053,514.5,3.4,conversions per LED 2; a = NIR only (temperatu...

=== 파일명: 예시_frames_v1.csv (크기: (90, 37)) ===
컬럼 목록: ['session', 'frame', 't_s', 'wear_min', 'A_1310', 'A_1370', 'A_1625', 'S21_dB_f1', 'S21_dB_f2', 'S21_dB_f3', 'S21_dB_f4', 'S21_dB_f5', 'S21_dB_f6', 'S21_deg_f1', 'S21_deg_f2', 'S21_deg_f3', 'S21_deg_f4', 'S21_deg_f5', 'S21_deg_f6', 'ntc_dT_C', 'fsr_N', 'glucose_mgdl', 'thickness_mm', 'dT_C', 'nuis_gain_dB', 'nuis_phase_deg', 'nuis_cable_mm', 'sigma_A_1310', 'sigma_A_1370', 'sigma_A_1625', 'sigma_S21_dB', 'sigma_S21_deg', 'sigma_ntc_C', 'sigma_fsr_N', 'n_avg', 'frame_period_s', 'design']

,session,frame,t_s,wear_min,A_1310,A_1370,A_1625,S21_dB_f1,S21_dB_f2,S21_dB_f3,...,sigma_A_1310,sigma_A_1370,sigma_A_1625,sigma_S21_dB,sigma_S21_deg,sigma_ntc_C,sigma_fsr_N,n_avg,frame_period_s,design
0,0,0,0,5.000000,-0.022414,-0.043906,-0.045904,-5.649334,-5.695201,-5.765537,...,0.000304,0.000305,0.000305,0.000079,0.000216,0.05,0.067861,860,20,1
1,0,1,20,5.333333,-0.021838,-0.043544,-0.047137,-5.649572,-5.695561,-5.765881,...,0.000304,0.000305,0.000305,0.000079,0.000216,0.05,0.069229,860,20,1

=== 파일명: NIR_계수표_v1.csv (크기: (13, 4)) ===
컬럼 목록: ['[phantom] 기준 두께 4.0 mm', 'A 1310 nm [mAU]', 'A 1370 nm [mAU]', 'A 1625 nm [mAU]']

  [phantom] 기준 두께 4.0 mm A 1310 nm [mAU] A 1370 nm [mAU] A 1625 nm [mAU]
0          혈당 +100 mg/dL         -0.1878         -0.3838         0.03906
1               온도 +1 °C           1.297           9.642          -12.19

=== 파일명: 통합모델_v1.csv (크기: (96, 7)) ===
컬럼 목록: ['table', 'label', 'mode', 'value_a', 'value_b', 'value_c', 'note']

,table,label,mode,value_a,value_b,value_c,note
0,predicted_sigma_glucose,"기준 (0 mg/dL, 4.0 mm, 0 °C)",nir,609.466190,NaN,NaN,mg/dL
1,predicted_sigma_glucose,"기준 (0 mg/dL, 4.0 mm, 0 °C)",mw,14.967756,NaN,NaN,mg/dL

=== 파일명: 구조비교_v1.csv (크기: (162, 4)) ===
컬럼 목록: ['table', 'label', 'col', 'value']

                    table     label         col   value
0  A_structure_sigma_mgdl  S21 (현재)    온도·두께 모름  14.792
1  A_structure_sigma_mgdl  S21 (현재)  온도 센서(NTC)  14.085

=== 파일명: 예시_frames_flag_v1.csv (크기: (90, 47)) ===
컬럼 목록: ['session', 'frame', 't_s', 'wear_min', 'A_1310', 'A_1370', 'A_1625', 'S21_dB_f1', 'S21_dB_f2', 'S21_dB_f3', 'S21_dB_f4', 'S21_dB_f5', 'S21_dB_f6', 'S21_deg_f1', 'S21_deg_f2', 'S21_deg_f3', 'S21_deg_f4', 'S21_deg_f5', 'S21_deg_f6', 'ntc_dT_C', 'fsr_N', 'glucose_mgdl', 'thickness_mm', 'dT_C', 'nuis_gain_dB', 'nuis_phase_deg', 'nuis_cable_mm', 'sigma_A_1310', 'sigma_A_1370', 'sigma_A_1625', 'sigma_S21_dB', 'sigma_S21_deg', 'sigma_ntc_C', 'sigma_fsr_N', 'n_avg', 'frame_period_s', 'design', 'glucose_hat_mgdl', 'fit_converged', 'resid_Q', 'resid_dof', 'resid_thresh', 'resid_p', 'flag_model_mismatch', 'resid_alpha', 'noise_kappa', 'resid_estimator']

,session,frame,t_s,wear_min,A_1310,A_1370,A_1625,S21_dB_f1,S21_dB_f2,S21_dB_f3,...,glucose_hat_mgdl,fit_converged,resid_Q,resid_dof,resid_thresh,resid_p,flag_model_mismatch,resid_alpha,noise_kappa,resid_estimator
0,0,0,0,5.000000,-0.022414,-0.043906,-0.045904,-5.649334,-5.695201,-5.765537,...,165.247383,1,2.68902,12,26.216967,0.997370,0,0.01,1,E0
1,0,1,20,5.333333,-0.021838,-0.043544,-0.047137,-5.649572,-5.695561,-5.765881,...,159.890858,1,10.74103,12,26.216967,0.551233,0,0.01,1,E0

=== 파일명: em_coeff_S11_v1_spectra.csv (크기: (741, 15)) ===
컬럼 목록: ['freq_GHz', 'S0_re', 'S0_im', 'dS_dblood_eps_re', 'dS_dblood_eps_im', 'dS_dblood_kappa_re', 'dS_dblood_kappa_im', 'dS_dskin_eps_re', 'dS_dskin_eps_im', 'dS_dtemp_re', 'dS_dtemp_im', 'S_gap3.5_re', 'S_gap3.5_im', 'S_gap4.5_re', 'S_gap4.5_im']

,freq_GHz,S0_re,S0_im,dS_dblood_eps_re,dS_dblood_eps_im,dS_dblood_kappa_re,dS_dblood_kappa_im,dS_dskin_eps_re,dS_dskin_eps_im,dS_dtemp_re,dS_dtemp_im,S_gap3.5_re,S_gap3.5_im,S_gap4.5_re,S_gap4.5_im
0,0.300,0.199508,0.025042,0.000014,0.000006,-0.001762,-0.003191,0.000041,0.000020,-0.000051,-0.000119,0.200019,0.026126,0.200072,0.025809
1,0.305,0.200327,0.025503,0.000014,0.000005,-0.001993,-0.003011,0.000044,0.000018,-0.000060,-0.000113,0.200924,0.026522,0.200957,0.026210

=== 파일명: 광자수송_v1.csv (크기: (591, 9)) ===
컬럼 목록: ['table', 'scenario', 'g', 'geometry', 'quantity', 'wl_1310', 'wl_1370', 'wl_1625', 'note']

,table,scenario,g,geometry,quantity,wl_1310,wl_1370,wl_1625,note
0,diffusion,phantom,NaN,NaN,T,0.099397,0.018005,0.011421,diffusion model (NIRLayerV1)
1,diffusion,phantom,NaN,NaN,glucose,-0.000188,-0.000384,0.000039,diffusion model (NIRLayerV1)

=== 파일명: Glucose_Level_Estimation.csv (크기: (249, 11)) ===
컬럼 목록: ['AGE', 'GENDER', 'WEIGHT', 'SKIN_COLOR', 'NIR_Reading', 'HEARTRATE', 'HEIGHT', 'LAST_EATEN', 'DIABETIC', 'HR_IR', 'GLUCOSE_LEVEL']

,AGE,GENDER,WEIGHT,SKIN_COLOR,NIR_Reading,HEARTRATE,HEIGHT,LAST_EATEN,DIABETIC,HR_IR,GLUCOSE_LEVEL
0,22,F,42.0,2,335.15,62.0,5.3,2.0,N,96762.0,110
1,22,F,76.0,2,574.25,98.0,5.8,3.0,N,94521.0,93

In [4]:
# 5. 훈련 데이터 한정 노이즈 추가 증강 (Augmentation)
def augment_sensor_data(X, y, noise_level=0.005, scaling_factor=0.01):
    noise = np.random.normal(0, noise_level, X.shape)
    X_jittered = X + noise
    factor = np.random.uniform(1 - scaling_factor, 1 + scaling_factor, size=(X.shape[0], 1))
    X_scaled = X * factor
    X_aug = np.vstack([X, X_jittered, X_scaled])
    y_aug = np.concatenate([y, y, y])
    return X_aug, y_aug

X_train_aug, y_train_aug = augment_sensor_data(X_train_scaled, y_train_raw)

# CNN 입력을 위한 텐서 차원 확장 [samples, features, channels]
X_train_exp = np.expand_dims(X_train_aug, axis=-1).astype(np.float32)
X_test_exp = np.expand_dims(X_test_scaled, axis=-1).astype(np.float32)
y_train_final = y_train_aug.astype(np.float32)
y_test_final = y_test_raw.astype(np.float32)

print(f"훈련 데이터 크기: {X_train_exp.shape}, 검증 데이터 크기: {X_test_exp.shape}")

훈련 데이터 크기: (180, 7, 1), 검증 데이터 크기: (30, 7, 1)

In [8]:
# 6. Conv1D 학습 모델 구성 및 학습
from tensorflow.keras import layers, callbacks

model = tf.keras.Sequential([
    layers.Input(shape=(7, 1)),
    layers.Conv1D(32, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.Conv1D(64, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.GlobalAveragePooling1D(),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(1, activation='linear')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='mse',
    metrics=['mae']
)

early_stopping = callbacks.EarlyStopping(
    monitor='val_loss',
    patience=20,
    restore_best_weights=True
)

history = model.fit(
    X_train_exp, y_train_final,
    validation_data=(X_test_exp, y_test_final),
    epochs=150,
    batch_size=16,
    callbacks=[early_stopping],
    verbose=1
)

best_val_mae = min(history.history['val_mae'])
print(f"\n[독립 세션 검증] 최종 검증 MAE: {best_val_mae:.4f} mg/dL")

Epoch 1/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 22032.6973 - mae: 147.3377 - val_loss: 22397.7695 - val_mae: 149.6583
Epoch 2/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21247.0938 - mae: 144.6507 - val_loss: 22225.6074 - val_mae: 149.0821
Epoch 3/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 20317.2227 - mae: 141.3877 - val_loss: 21962.9688 - val_mae: 148.1986
Epoch 4/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 19235.9766 - mae: 137.5374 - val_loss: 21600.8926 - val_mae: 146.9720
Epoch 5/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 17908.9023 - mae: 132.6583 - val_loss: 21099.6777 - val_mae: 145.2570
Epoch 6/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 16691.9941 - mae: 127.9635 - val_loss: 20554.0234 - val_mae: 143.3665
Epoch 7/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 14815.3711 - mae: 120.2684 - val_loss: 19922.4629 - val_mae: 141.1468
Epoch 8/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13312.0449 - mae: 113.9747 - val_loss: 19086.9414 - val_mae: 138.1553
Epoch 9/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11488.0146 - mae: 105.5426 - val_loss: 18145.1602 - val_mae: 134.7038
Epoch 10/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9575.2705 - mae: 95.7839 - val_loss: 17155.3145 - val_mae: 130.9781
Epoch 11/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7895.6450 - mae: 86.5571 - val_loss: 15955.9189 - val_mae: 126.3165
Epoch 12/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6106.5640 - mae: 74.9275 - val_loss: 14921.9189 - val_mae: 122.1550
Epoch 13/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5036.9604 - mae: 66.8901 - val_loss: 13801.2158 - val_mae: 117.4782
Epoch 14/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3872.2209 - mae: 56.7943 - val_loss: 12790.4561 - val_mae: 113.0945
Epoch 15/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2827.2668 - mae: 47.5926 - val_loss: 11780.3525 - val_mae: 108.5368
Epoch 16/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2210.6733 - mae: 40.6904 - val_loss: 10765.5156 - val_mae: 103.7564
Epoch 17/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1898.8800 - mae: 37.2666 - val_loss: 9879.9248 - val_mae: 99.3971
Epoch 18/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1653.6953 - mae: 33.9032 - val_loss: 9259.4131 - val_mae: 96.2251
Epoch 19/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1703.8948 - mae: 34.0268 - val_loss: 8745.2305 - val_mae: 93.5153
Epoch 20/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1533.9152 - mae: 32.8520 - val_loss: 8362.9707 - val_mae: 91.4487
Epoch 21/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1375.9824 - mae: 29.9968 - val_loss: 7816.1362 - val_mae: 88.4083
Epoch 22/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1396.6556 - mae: 31.0332 - val_loss: 7346.2671 - val_mae: 85.7097
Epoch 23/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1404.9347 - mae: 30.0520 - val_loss: 6783.2974 - val_mae: 82.3600
Epoch 24/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1495.9536 - mae: 32.0189 - val_loss: 6970.1172 - val_mae: 83.4867
Epoch 25/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1445.4144 - mae: 31.2115 - val_loss: 6385.0020 - val_mae: 79.9056
Epoch 26/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1423.8147 - mae: 30.9850 - val_loss: 7012.3447 - val_mae: 83.7388
Epoch 27/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1439.8522 - mae: 30.6004 - val_loss: 7147.7095 - val_mae: 84.5425
Epoch 28/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1437.5245 - mae: 30.5003 - val_loss: 6329.3901 - val_mae: 79.5565
Epoch 29/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1342.6051 - mae: 30.6294 - val_loss: 6483.5776 - val_mae: 80.5198
Epoch 30/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1380.8967 - mae: 30.6311 - val_loss: 6185.7798 - val_mae: 78.6488
Epoch 31/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1627.5608 - mae: 33.6217 - val_loss: 7535.0938 - val_mae: 86.8002
Epoch 32/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1356.0922 - mae: 30.1453 - val_loss: 8233.8262 - val_mae: 90.7359
Epoch 33/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1535.3660 - mae: 32.8672 - val_loss: 3897.4509 - val_mae: 62.4279
Epoch 34/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1433.9918 - mae: 31.7120 - val_loss: 1546.8590 - val_mae: 39.3258
Epoch 35/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1363.2227 - mae: 30.2259 - val_loss: 1597.9722 - val_mae: 39.9706
Epoch 36/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1545.5413 - mae: 32.4190 - val_loss: 2038.2474 - val_mae: 45.1438
Epoch 37/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1559.0317 - mae: 32.2108 - val_loss: 2777.7024 - val_mae: 52.7008
Epoch 38/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1629.8640 - mae: 33.0771 - val_loss: 3384.0952 - val_mae: 58.1671
Epoch 39/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1548.1134 - mae: 32.4037 - val_loss: 3591.9062 - val_mae: 59.9258
Epoch 40/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1457.2965 - mae: 30.6909 - val_loss: 3277.7280 - val_mae: 57.2440
Epoch 41/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1136.9298 - mae: 27.7532 - val_loss: 3267.1636 - val_mae: 57.1515
Epoch 42/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1513.8540 - mae: 31.6246 - val_loss: 5184.9189 - val_mae: 71.9973
Epoch 43/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1467.1267 - mae: 32.2162 - val_loss: 3631.8828 - val_mae: 60.2554
Epoch 44/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1394.1995 - mae: 30.1200 - val_loss: 3162.8516 - val_mae: 56.2241
Epoch 45/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1419.3771 - mae: 30.4851 - val_loss: 2601.8369 - val_mae: 50.9958
Epoch 46/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1353.6410 - mae: 31.0580 - val_loss: 3032.3162 - val_mae: 55.0531
Epoch 47/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1487.6927 - mae: 32.4656 - val_loss: 4048.8826 - val_mae: 63.6160
Epoch 48/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1363.1768 - mae: 30.7112 - val_loss: 5055.1543 - val_mae: 71.0824
Epoch 49/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1442.7229 - mae: 31.4532 - val_loss: 4737.3418 - val_mae: 68.8111
Epoch 50/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1290.1064 - mae: 29.7890 - val_loss: 3499.7427 - val_mae: 59.1411
Epoch 51/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1429.9491 - mae: 30.9843 - val_loss: 3741.4985 - val_mae: 61.1471
Epoch 52/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1461.2943 - mae: 31.6904 - val_loss: 5039.7012 - val_mae: 70.9737
Epoch 53/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1288.8959 - mae: 29.6430 - val_loss: 4579.1670 - val_mae: 67.6476
Epoch 54/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1298.4005 - mae: 29.8367 - val_loss: 3610.2456 - val_mae: 60.0599

[독립 세션 검증] 최종 검증 MAE: 39.3258 mg/dL

In [12]:
# 7. Keras 모델 영속 저장 및 동적 범위 양자화 (TFLite Converter)
model.save(os.path.join(SAVE_DIR, 'glucose_model_combined.h5'))

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

tflite_path = os.path.join(SAVE_DIR, 'glucose_model_combined.tflite')
with open(tflite_path, 'wb') as f:
    f.write(tflite_model)

print(f"배포용 양자화 TFLite 모델 저장 완료: {tflite_path}")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Saved artifact at '/tmp/tmp80kuypfg'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 7, 1), dtype=tf.float32, name='keras_tensor')
Output Type:
  TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)
Captures:
  136031761638864: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761638672: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761637712: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761639248: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761639632: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761639440: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761640400: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761639824: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761640208: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761641168: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761639056: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761641360: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761640784: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761642128: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761641936: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136031761642512: TensorSpec(shape=(), dtype=tf.resource, name=None)
배포용 양자화 TFLite 모델 저장 완료: /content/drive/MyDrive/Glucose_Model_Output/glucose_model_combined.tflite


1. **이종 데이터 결합 배제**: Kaggle 데이터를 섞지 않고 오직 우리 센서 데이터(`예시_frames_v1.csv`)만 학습에 사용합
2. **엄격한 세션 분할**: 무작위 분할 대신 세션 1, 2를 훈련셋, 세션 3을 독립 평가용 테스트셋으로 분리
3. **선 분할 후 증강**: 훈련셋에만 증강을 수행하여 데이터 누수를 완벽히 차단
4. **스케일러 파라미터 내보내기**: 임베디드 배포를 위해 스케일러 파라미터(`mean`, `scale`)를 JSON으로 명시적 저장

In [13]:
import os
import json
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler

# 1. 경로 설정 및 데이터 로드
SAVE_DIR = '/content/drive/MyDrive/Glucose_Model_Output'
os.makedirs(SAVE_DIR, exist_ok=True)

# 메모리에 이미 정상 로드된 drive_df가 있으면 우선 사용, 없으면 파일 로드
try:
    if 'drive_df' in globals() and isinstance(drive_df, pd.DataFrame) and not drive_df.empty:
        print("메모리에 이미 로딩된 데이터프레임을 재사용합니다. (크기: ", drive_df.shape, ")")
    else:
        drive_csv_path = '/content/drive/MyDrive/data/예시_frames_v1.csv'
        drive_df = pd.read_csv(drive_csv_path)
        print("파일로부터 데이터를 신규 로드했습니다. (크기: ", drive_df.shape, ")")
except Exception as e:
    raise FileNotFoundError(f"데이터 로드 실패: {e}. 앞의 드라이브 리마운트 및 탐색 셀을 먼저 실행해 주세요.")

# 피처 및 타겟 정의
feature_cols = ['A_1310', 'A_1370', 'A_1625', 'S21_dB_f1', 'S21_dB_f2', 'S21_dB_f3', 'S21_dB_f4']
target_col = 'glucose_mgdl'

# 수치형 데이터 변환 및 결측치 제거
for col in feature_cols + [target_col]:
    drive_df[col] = pd.to_numeric(drive_df[col], errors='coerce')
drive_df = drive_df.dropna(subset=[target_col]).fillna(0)

# 2. 세션 기반 분할 (Session-based Split)
unique_sessions = sorted(drive_df['session'].unique())
print(f"전체 세션 목록: {unique_sessions}")

# 마지막 세션을 독립 테스트셋으로 엄격 격리
test_sessions = [unique_sessions[-1]]
train_sessions = [s for s in unique_sessions if s not in test_sessions]

train_df = drive_df[drive_df['session'].isin(train_sessions)].copy()
test_df = drive_df[drive_df['session'].isin(test_sessions)].copy()

X_train_raw = train_df[feature_cols].values
y_train_raw = train_df[target_col].values
X_test_raw = test_df[feature_cols].values
y_test_raw = test_df[target_col].values

print(f"훈련 세션 {train_sessions} 데이터 수: {X_train_raw.shape[0]}개")
print(f"테스트 세션 {test_sessions} 데이터 수: {X_test_raw.shape[0]}개")

# 3. 훈련 데이터에 대해서만 정규화 적합 (Fit)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_raw)
X_test_scaled = scaler.transform(X_test_raw)

# 스케일러 파라미터 배포용 JSON 저장
scaler_params = {
    "mean": scaler.mean_.tolist(),
    "scale": scaler.scale_.tolist()
}
with open(os.path.join(SAVE_DIR, "scaler_params.json"), "w") as f:
    json.dump(scaler_params, f, indent=4)
print(f"배포용 스케일러 파라미터 저장 완료: {SAVE_DIR}/scaler_params.json")

메모리에 이미 로딩된 데이터프레임을 재사용합니다. (크기:  (90, 37) )
전체 세션 목록: [np.int64(0), np.int64(1), np.int64(2)]
훈련 세션 [np.int64(0), np.int64(1)] 데이터 수: 60개
테스트 세션 [np.int64(2)] 데이터 수: 30개
배포용 스케일러 파라미터 저장 완료: /content/drive/MyDrive/Glucose_Model_Output/scaler_params.json

In [ ]:
# 4. 오직 훈련 데이터에만 데이터 증강(Augmentation) 적용 (Leakage 차단)
def augment_only_train(X, y, noise_level=0.005, scaling_factor=0.01):
    # 센서 변동성에 맞춰 노이즈 강도 현실적으로 조정
    noise = np.random.normal(0, noise_level, X.shape)
    X_jittered = X + noise

    factor = np.random.uniform(1 - scaling_factor, 1 + scaling_factor, size=(X.shape[0], 1))
    X_scaled = X * factor

    X_aug = np.vstack([X, X_jittered, X_scaled])
    y_aug = np.concatenate([y, y, y])
    return X_aug, y_aug

X_train_aug, y_train_aug = augment_only_train(X_train_scaled, y_train_raw)
print(f"훈련셋 증강 완료: {X_train_scaled.shape[0]}개 -> {X_train_aug.shape[0]}개")

# 텐서 차원 확장
X_train_exp = np.expand_dims(X_train_aug, axis=-1).astype(np.float32)
X_test_exp = np.expand_dims(X_test_scaled, axis=-1).astype(np.float32)
y_train_final = y_train_aug.astype(np.float32)
y_test_final = y_test_raw.astype(np.float32)

훈련셋 증강 완료: 70개 -> 210개

In [ ]:
# 5. 규제화 모델 학습 및 진성 검증 수치 확인
from tensorflow.keras import layers, models, callbacks

model = tf.keras.Sequential([
    layers.Input(shape=(7, 1)),
    layers.Conv1D(32, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.Conv1D(64, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.GlobalAveragePooling1D(),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(1, activation='linear')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='mse',
    metrics=['mae']
)

early_stopping = callbacks.EarlyStopping(
    monitor='val_loss',
    patience=20,
    restore_best_weights=True
)

# 훈련 시작
history = model.fit(
    X_train_exp, y_train_final,
    validation_data=(X_test_exp, y_test_final),
    epochs=150,
    batch_size=16,
    callbacks=[early_stopping],
    verbose=1
)

best_val_mae = min(history.history['val_mae'])
print(f"\n[진성 독립 세션 검증] 최종 검증 MAE: {best_val_mae:.4f} mg/dL")

Epoch 1/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 14369.2764 - mae: 116.9748 - val_loss: 14523.0566 - val_mae: 117.8451
Epoch 2/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14082.2617 - mae: 115.7421 - val_loss: 14469.3262 - val_mae: 117.6179
Epoch 3/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13743.5889 - mae: 114.2464 - val_loss: 14384.2627 - val_mae: 117.2615
Epoch 4/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13248.2549 - mae: 112.0503 - val_loss: 14225.1641 - val_mae: 116.5925
Epoch 5/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12562.3818 - mae: 108.8574 - val_loss: 13959.6426 - val_mae: 115.4629
Epoch 6/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 11817.8330 - mae: 105.2127 - val_loss: 13570.2607 - val_mae: 113.7868
Epoch 7/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10725.1484 - mae: 99.6680 - val_loss: 13075.9639 - val_mae: 111.6185
Epoch 8/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9706.6348 - mae: 93.9931 - val_loss: 12466.6270 - val_mae: 108.8689
Epoch 9/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8399.1533 - mae: 85.9939 - val_loss: 11752.7793 - val_mae: 105.5336
Epoch 10/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7163.3145 - mae: 78.3245 - val_loss: 10964.2314 - val_mae: 101.6939
Epoch 11/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6143.2563 - mae: 70.0963 - val_loss: 10253.6670 - val_mae: 98.0053
Epoch 12/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5056.0820 - mae: 62.3042 - val_loss: 9701.0312 - val_mae: 94.8444
Epoch 13/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4277.6045 - mae: 55.4865 - val_loss: 9177.8447 - val_mae: 91.7583
Epoch 14/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3800.0518 - mae: 51.4633 - val_loss: 8675.6777 - val_mae: 88.6444
Epoch 15/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3281.0149 - mae: 47.4283 - val_loss: 8348.9688 - val_mae: 86.5937
Epoch 16/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3089.1560 - mae: 45.4910 - val_loss: 7928.8672 - val_mae: 83.8385
Epoch 17/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2908.7178 - mae: 44.4764 - val_loss: 7822.3491 - val_mae: 82.9159
Epoch 18/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2735.0283 - mae: 42.9367 - val_loss: 7681.0693 - val_mae: 82.0358
Epoch 19/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2512.2383 - mae: 40.9929 - val_loss: 7316.8174 - val_mae: 79.5347
Epoch 20/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2470.1262 - mae: 41.3156 - val_loss: 7129.6406 - val_mae: 78.3348
Epoch 21/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2218.4106 - mae: 38.2825 - val_loss: 7104.0952 - val_mae: 78.2158
Epoch 22/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2070.6404 - mae: 36.8470 - val_loss: 6747.7471 - val_mae: 75.8914
Epoch 23/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2193.6970 - mae: 38.3930 - val_loss: 6410.8677 - val_mae: 73.2824
Epoch 24/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1915.7841 - mae: 35.5750 - val_loss: 6253.8643 - val_mae: 71.7346
Epoch 25/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1806.9572 - mae: 34.6819 - val_loss: 5650.0391 - val_mae: 67.5221
Epoch 26/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1767.8527 - mae: 34.8634 - val_loss: 5587.7188 - val_mae: 66.2826
Epoch 27/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1650.2050 - mae: 32.4884 - val_loss: 5232.5171 - val_mae: 63.4305
Epoch 28/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1635.4033 - mae: 32.0334 - val_loss: 4829.4072 - val_mae: 60.0582
Epoch 29/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1431.3826 - mae: 31.2283 - val_loss: 4609.2783 - val_mae: 58.7426
Epoch 30/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1257.6105 - mae: 28.4978 - val_loss: 4541.3862 - val_mae: 57.9612
Epoch 31/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1343.8162 - mae: 28.8035 - val_loss: 4250.2959 - val_mae: 56.6546
Epoch 32/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1397.5238 - mae: 29.9068 - val_loss: 4096.3462 - val_mae: 55.2771
Epoch 33/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1250.3978 - mae: 29.0873 - val_loss: 3824.4915 - val_mae: 54.0234
Epoch 34/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1107.2815 - mae: 26.0411 - val_loss: 3744.7944 - val_mae: 53.1486
Epoch 35/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1107.9338 - mae: 26.6984 - val_loss: 3467.8281 - val_mae: 51.3079
Epoch 36/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1120.1283 - mae: 25.5714 - val_loss: 3481.9055 - val_mae: 51.4906
Epoch 37/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1054.3158 - mae: 26.4198 - val_loss: 3205.8364 - val_mae: 49.0541
Epoch 38/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1016.7375 - mae: 25.4629 - val_loss: 3235.9409 - val_mae: 49.1658
Epoch 39/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 891.8730 - mae: 23.8879 - val_loss: 3182.4690 - val_mae: 48.5399
Epoch 40/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 985.5374 - mae: 24.7731 - val_loss: 3386.3062 - val_mae: 50.2127
Epoch 41/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 981.5351 - mae: 24.9591 - val_loss: 3019.9871 - val_mae: 46.6883
Epoch 42/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 866.5734 - mae: 23.0250 - val_loss: 3009.0659 - val_mae: 45.6399
Epoch 43/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 759.7842 - mae: 22.3470 - val_loss: 2739.3354 - val_mae: 44.3665
Epoch 44/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 848.7150 - mae: 22.6188 - val_loss: 2968.8982 - val_mae: 45.1735
Epoch 45/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 759.2317 - mae: 21.3606 - val_loss: 2796.6450 - val_mae: 43.7632
Epoch 46/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 765.4437 - mae: 22.0520 - val_loss: 2655.4348 - val_mae: 41.9975
Epoch 47/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 592.2670 - mae: 18.5952 - val_loss: 2837.8293 - val_mae: 43.0213
Epoch 48/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 650.5780 - mae: 20.7571 - val_loss: 2754.0984 - val_mae: 41.8194
Epoch 49/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 607.9300 - mae: 18.9554 - val_loss: 2651.4814 - val_mae: 41.6131
Epoch 50/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 666.1500 - mae: 20.6057 - val_loss: 2594.0356 - val_mae: 40.9583
Epoch 51/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 671.5878 - mae: 20.4898 - val_loss: 2902.1733 - val_mae: 42.4129
Epoch 52/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 766.7219 - mae: 21.7735 - val_loss: 2567.2876 - val_mae: 41.3170
Epoch 53/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 621.8246 - mae: 19.7222 - val_loss: 2675.2241 - val_mae: 40.9834
Epoch 54/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 623.6079 - mae: 19.7436 - val_loss: 2832.0322 - val_mae: 42.1339
Epoch 55/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 609.2396 - mae: 19.1363 - val_loss: 2857.3254 - val_mae: 41.9277
Epoch 56/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 514.1863 - mae: 18.4036 - val_loss: 2838.4548 - val_mae: 41.7072
Epoch 57/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 550.9775 - mae: 18.9070 - val_loss: 2618.7585 - val_mae: 40.7524
Epoch 58/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 514.3123 - mae: 18.0491 - val_loss: 2711.3809 - val_mae: 40.8557
Epoch 59/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 613.9520 - mae: 19.2883 - val_loss: 2760.0486 - val_mae: 42.2529
Epoch 60/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 580.0155 - mae: 19.2084 - val_loss: 2783.0466 - val_mae: 40.4057
Epoch 61/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 529.9033 - mae: 18.9287 - val_loss: 2610.7134 - val_mae: 38.8694
Epoch 62/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 524.5314 - mae: 17.9686 - val_loss: 2815.9387 - val_mae: 41.5607
Epoch 63/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 549.2066 - mae: 18.3289 - val_loss: 2712.5510 - val_mae: 41.2868
Epoch 64/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 545.1930 - mae: 18.6612 - val_loss: 2747.5046 - val_mae: 42.1645
Epoch 65/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 562.5175 - mae: 18.1891 - val_loss: 2885.6772 - val_mae: 42.8176
Epoch 66/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 492.4721 - mae: 17.9111 - val_loss: 2549.0828 - val_mae: 40.4852
Epoch 67/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 411.2513 - mae: 15.4579 - val_loss: 2641.6519 - val_mae: 41.0325
Epoch 68/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 529.2132 - mae: 18.0596 - val_loss: 2379.4368 - val_mae: 37.5232
Epoch 69/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 486.5153 - mae: 17.7196 - val_loss: 2784.3330 - val_mae: 42.3565
Epoch 70/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 497.7200 - mae: 17.7974 - val_loss: 2320.8445 - val_mae: 38.3199
Epoch 71/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 504.2651 - mae: 18.1754 - val_loss: 2088.5615 - val_mae: 37.3613
Epoch 72/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 640.6091 - mae: 19.9459 - val_loss: 2220.4873 - val_mae: 37.8138
Epoch 73/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 442.7119 - mae: 16.2357 - val_loss: 2102.3850 - val_mae: 36.4210
Epoch 74/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 451.9113 - mae: 16.0998 - val_loss: 2326.8347 - val_mae: 37.9862
Epoch 75/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 480.1328 - mae: 16.7767 - val_loss: 2110.0261 - val_mae: 36.4214
Epoch 76/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 453.1508 - mae: 16.9048 - val_loss: 2349.1812 - val_mae: 38.1955
Epoch 77/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 450.3748 - mae: 16.4640 - val_loss: 2047.2295 - val_mae: 35.8827
Epoch 78/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 466.8922 - mae: 16.9985 - val_loss: 2189.4949 - val_mae: 36.5752
Epoch 79/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 414.6323 - mae: 16.5160 - val_loss: 2009.9388 - val_mae: 36.2920
Epoch 80/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 410.8713 - mae: 15.8402 - val_loss: 2214.6758 - val_mae: 38.1586
Epoch 81/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 489.3032 - mae: 16.8778 - val_loss: 2346.9858 - val_mae: 37.3810
Epoch 82/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 467.3798 - mae: 16.2854 - val_loss: 2000.3226 - val_mae: 35.3539
Epoch 83/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 471.6728 - mae: 17.2248 - val_loss: 2368.6038 - val_mae: 39.2659
Epoch 84/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 460.6124 - mae: 16.6028 - val_loss: 2171.6472 - val_mae: 37.7335
Epoch 85/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 395.5381 - mae: 16.1905 - val_loss: 1934.2096 - val_mae: 36.1058
Epoch 86/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 491.3212 - mae: 17.4885 - val_loss: 1966.0498 - val_mae: 35.5929
Epoch 87/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 375.7802 - mae: 14.5944 - val_loss: 2573.5847 - val_mae: 40.0121
Epoch 88/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 384.5797 - mae: 16.0863 - val_loss: 2047.1047 - val_mae: 36.3418
Epoch 89/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 385.2872 - mae: 15.6971 - val_loss: 2095.3486 - val_mae: 35.2951
Epoch 90/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 580.1112 - mae: 18.6945 - val_loss: 1897.4860 - val_mae: 33.4847
Epoch 91/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 478.1721 - mae: 17.6026 - val_loss: 1988.7219 - val_mae: 35.1244
Epoch 92/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 426.9900 - mae: 15.9897 - val_loss: 1813.6592 - val_mae: 34.6249
Epoch 93/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 487.0352 - mae: 17.5062 - val_loss: 1898.8834 - val_mae: 34.3475
Epoch 94/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 459.0365 - mae: 16.1918 - val_loss: 2162.9243 - val_mae: 35.5386
Epoch 95/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 371.5301 - mae: 15.1500 - val_loss: 1988.7467 - val_mae: 34.7280
Epoch 96/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 491.6276 - mae: 17.3726 - val_loss: 2044.8088 - val_mae: 36.9807
Epoch 97/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 385.1815 - mae: 15.0118 - val_loss: 2076.5601 - val_mae: 36.1232
Epoch 98/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 385.0533 - mae: 15.6389 - val_loss: 2232.4878 - val_mae: 37.0438
Epoch 99/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 415.9670 - mae: 15.8142 - val_loss: 2097.1648 - val_mae: 36.3442
Epoch 100/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 413.3040 - mae: 16.2466 - val_loss: 2011.1934 - val_mae: 36.3091
Epoch 101/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 445.2652 - mae: 16.6814 - val_loss: 1874.0416 - val_mae: 36.2081
Epoch 102/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 423.6812 - mae: 16.1367 - val_loss: 1947.0491 - val_mae: 35.8746
Epoch 103/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 385.6192 - mae: 15.6435 - val_loss: 1879.9221 - val_mae: 35.2847
Epoch 104/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 330.8828 - mae: 14.6249 - val_loss: 1839.1342 - val_mae: 34.9528
Epoch 105/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 407.1756 - mae: 15.4515 - val_loss: 1947.7478 - val_mae: 34.4240
Epoch 106/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 363.4034 - mae: 14.9056 - val_loss: 1859.0280 - val_mae: 35.3629
Epoch 107/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 414.8733 - mae: 16.1370 - val_loss: 1745.2605 - val_mae: 34.0082
Epoch 108/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 347.9497 - mae: 14.1684 - val_loss: 1846.6240 - val_mae: 34.8356
Epoch 109/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 345.7681 - mae: 14.1755 - val_loss: 1947.6414 - val_mae: 35.8965
Epoch 110/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 391.1336 - mae: 15.6961 - val_loss: 1683.0443 - val_mae: 33.3610
Epoch 111/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 435.8028 - mae: 16.5879 - val_loss: 1816.7260 - val_mae: 33.3916
Epoch 112/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 415.0571 - mae: 15.6340 - val_loss: 1822.6107 - val_mae: 34.5068
Epoch 113/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 424.8437 - mae: 16.2175 - val_loss: 1742.9016 - val_mae: 34.0420
Epoch 114/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 400.9393 - mae: 15.8078 - val_loss: 1794.0209 - val_mae: 34.8496
Epoch 115/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 410.1989 - mae: 15.8732 - val_loss: 1936.1393 - val_mae: 35.9763
Epoch 116/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 392.9872 - mae: 15.6064 - val_loss: 1450.9915 - val_mae: 31.9595
Epoch 117/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 427.0138 - mae: 15.5508 - val_loss: 1858.2410 - val_mae: 34.6136
Epoch 118/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 334.4508 - mae: 14.6769 - val_loss: 1948.0817 - val_mae: 34.7477
Epoch 119/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - loss: 360.4360 - mae: 14.8108 - val_loss: 1562.0929 - val_mae: 32.2234
Epoch 120/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 342.7938 - mae: 14.2535 - val_loss: 1743.9785 - val_mae: 33.7194
Epoch 121/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 356.6312 - mae: 14.6461 - val_loss: 1689.8480 - val_mae: 33.8476
Epoch 122/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 352.3549 - mae: 14.4979 - val_loss: 1615.2100 - val_mae: 32.8386
Epoch 123/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 396.1203 - mae: 15.4700 - val_loss: 1536.2278 - val_mae: 31.8754
Epoch 124/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 359.2376 - mae: 14.7057 - val_loss: 1529.6326 - val_mae: 31.4349
Epoch 125/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 296.8486 - mae: 13.5057 - val_loss: 1736.9153 - val_mae: 33.7164
Epoch 126/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 382.1541 - mae: 14.9203 - val_loss: 1734.8051 - val_mae: 33.0387
Epoch 127/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 333.6096 - mae: 14.5523 - val_loss: 1703.1953 - val_mae: 33.8690
Epoch 128/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 333.4858 - mae: 14.1955 - val_loss: 1678.9476 - val_mae: 33.4215
Epoch 129/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 390.9950 - mae: 15.1170 - val_loss: 1587.5461 - val_mae: 32.0468
Epoch 130/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 395.8920 - mae: 15.3215 - val_loss: 1680.6002 - val_mae: 33.4888
Epoch 131/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 334.4764 - mae: 14.6783 - val_loss: 1721.8357 - val_mae: 33.5321
Epoch 132/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 360.8736 - mae: 14.5148 - val_loss: 1681.6940 - val_mae: 33.4959
Epoch 133/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 397.1243 - mae: 15.4770 - val_loss: 1976.8063 - val_mae: 35.7145
Epoch 134/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 367.2407 - mae: 15.0233 - val_loss: 1748.6959 - val_mae: 34.3416
Epoch 135/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 347.5085 - mae: 14.7955 - val_loss: 1834.6312 - val_mae: 34.4992
Epoch 136/150
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 394.0602 - mae: 14.8958 - val_loss: 1750.5442 - val_mae: 34.0425

[진성 독립 세션 검증] 최종 검증 MAE: 31.4349 mg/dL

In [ ]:
# 6.  TFLite 내보내기
model.save(f'{SAVE_DIR}/glucose_model_combined.h5')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

with open(f'{SAVE_DIR}/glucose_model_combined.tflite', 'wb') as f:
    f.write(tflite_model)

print(f" 무누수 검증을 마친 TFLite 모델 저장 완료: {SAVE_DIR}/glucose_model_combined.tflite")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Saved artifact at '/tmp/tmprj48n4wb'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 7, 1), dtype=tf.float32, name='keras_tensor_48')
Output Type:
  TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)
Captures:
  135991297846800: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297848720: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297848912: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297847568: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297846608: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297848528: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297850448: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297846416: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297847184: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297846224: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297847376: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297846992: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297840464: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135991297848336: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135992371002832: TensorSpec(shape=(), dtype=tf.resource, name=None)
  135992371001296: TensorSpec(shape=(), dtype=tf.resource, name=None)
 무누수 검증을 마친 TFLite 모델 저장 완료: /content/drive/MyDrive/Glucose_Model_Output/glucose_model_combined.tflite